branch-defaults:
  default:
    environment: health-env4
    group_suffix: null
environment-defaults:
  health-env4:
    branch: null
    repository: null
global:
  application_name: health-score
  branch: null
  default_ec2_keyname: health-eb
  default_platform: Python 3.9
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
